// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18LabQuery.Models;

public partial class Student
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public int Mark { get; set; }

    [StringLength(50)]
    public string Class { get; set; }

    public bool IsDelete { get; set; }

    [StringLength(50)]
    public string Subject { get; set; }
}