// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Table("AssetManagement")]
public partial class AssetManagement
{
    [Key]
    public int AssetID { get; set; }

    [StringLength(100)]
    public string AssetName { get; set; }

    [StringLength(100)]
    public string SerialNumber { get; set; }

    public int? AssignedTo { get; set; }

    [Column(TypeName = "date")]
    public DateTime? AssignedDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? ReturnDate { get; set; }

    [StringLength(50)]
    public string Status { get; set; }
}