// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Table("Attendance")]
public partial class Attendance
{
    [Key]
    public int AttendanceID { get; set; }

    public int? EmployeeID { get; set; }

    [Column(TypeName = "date")]
    public DateTime? Date { get; set; }

    public TimeSpan? CheckIn { get; set; }

    public TimeSpan? CheckOut { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("Attendances")]
    public virtual Employee Employee { get; set; }
}