// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Table("BenefitsCompensation")]
public partial class BenefitsCompensation
{
    [Key]
    public int BenefitID { get; set; }

    public int? EmployeeID { get; set; }

    [StringLength(100)]
    public string BenefitType { get; set; }

    [Column(TypeName = "date")]
    public DateTime? StartDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? EndDate { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Value { get; set; }
}