// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Table("Candidate")]
[Index("Email", Name = "UQ__Candidat__A9D10534F82F6DCE", IsUnique = true)]
public partial class Candidate
{
    [Key]
    public int CandidateID { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(20)]
    public string Phone { get; set; }

    public string Resume { get; set; }

    public int? AppliedJobID { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [InverseProperty("Candidate")]
    public virtual ICollection<Interview> Interviews { get; set; } = new List<Interview>();
}