// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

public partial class DisciplinaryAction
{
    [Key]
    public int ActionID { get; set; }

    public int? EmployeeID { get; set; }

    [Column(TypeName = "date")]
    public DateTime? Date { get; set; }

    [StringLength(100)]
    public string ActionType { get; set; }

    public string Notes { get; set; }

    public int? TakenBy { get; set; }
}