// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Table("DocumentManagement")]
public partial class DocumentManagement
{
    [Key]
    public int DocumentID { get; set; }

    public int? EmployeeID { get; set; }

    [StringLength(100)]
    public string DocumentType { get; set; }

    [Column(TypeName = "date")]
    public DateTime? UploadDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? ExpiryDate { get; set; }

    [StringLength(200)]
    public string FilePath { get; set; }
}