// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Table("Employee")]
[Index("Email", Name = "UQ__Employee__A9D10534200CD8DA", IsUnique = true)]
public partial class Employee
{
    [Key]
    public int EmployeeID { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(20)]
    public string Phone { get; set; }

    [Column(TypeName = "date")]
    public DateTime? HireDate { get; set; }

    public int? JobID { get; set; }

    public int? DepartmentID { get; set; }

    public int? SalaryID { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<Attendance> Attendances { get; set; } = new List<Attendance>();

    [ForeignKey("DepartmentID")]
    [InverseProperty("Employees")]
    public virtual LkpHRDepartment Department { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<Employee_Training> Employee_Trainings { get; set; } = new List<Employee_Training>();

    [ForeignKey("JobID")]
    [InverseProperty("Employees")]
    public virtual Job Job { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<Leave> Leaves { get; set; } = new List<Leave>();

    [InverseProperty("Employee")]
    public virtual ICollection<Onboarding> Onboardings { get; set; } = new List<Onboarding>();

    [InverseProperty("Employee")]
    public virtual ICollection<PerformanceEvaluation> PerformanceEvaluations { get; set; } = new List<PerformanceEvaluation>();

    [InverseProperty("Employee")]
    public virtual ICollection<Project_Assignment> Project_Assignments { get; set; } = new List<Project_Assignment>();

    [InverseProperty("Employee")]
    public virtual ICollection<Salary> Salaries { get; set; } = new List<Salary>();

    [InverseProperty("Employee")]
    public virtual ICollection<Survey_Response> Survey_Responses { get; set; } = new List<Survey_Response>();

    [InverseProperty("Employee")]
    public virtual User User { get; set; }
}