// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[PrimaryKey("EmployeeID", "TrainingID")]
[Table("Employee_Training")]
public partial class Employee_Training
{
    [Key]
    public int EmployeeID { get; set; }

    [Key]
    public int TrainingID { get; set; }

    [StringLength(50)]
    public string CompletionStatus { get; set; }

    public int? Score { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("Employee_Trainings")]
    public virtual Employee Employee { get; set; }

    [ForeignKey("TrainingID")]
    [InverseProperty("Employee_Trainings")]
    public virtual Training Training { get; set; }
}