// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Keyless]
public partial class HRNeedRequest
{
    [StringLength(10)]
    public string Id { get; set; }

    [StringLength(10)]
    public string DepartmentId { get; set; }

    [StringLength(10)]
    public string Title { get; set; }

    [StringLength(10)]
    public string Qunatity { get; set; }
}