// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Table("Interview")]
public partial class Interview
{
    [Key]
    public int InterviewID { get; set; }

    public int? CandidateID { get; set; }

    public int? RecruiterID { get; set; }

    [Column(TypeName = "date")]
    public DateTime? Date { get; set; }

    [StringLength(50)]
    public string Result { get; set; }

    [ForeignKey("CandidateID")]
    [InverseProperty("Interviews")]
    public virtual Candidate Candidate { get; set; }

    [ForeignKey("RecruiterID")]
    [InverseProperty("Interviews")]
    public virtual Recruiter Recruiter { get; set; }
}