// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

public partial class LeaveType
{
    [Key]
    public int LeaveTypeId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [InverseProperty("LeaveType")]
    public virtual ICollection<Leave> Leaves { get; set; } = new List<Leave>();
}