// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Table("Leave")]
public partial class Leave
{
    public int LeaveID { get; set; }

    public int? EmployeeID { get; set; }

    public int? LeaveTypeId { get; set; }

    public int? Quantity { get; set; }

    [Key]
    [Column(TypeName = "date")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? EndDate { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    public int? ApprovedBy { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("Leaves")]
    public virtual Employee Employee { get; set; }

    [ForeignKey("LeaveTypeId")]
    [InverseProperty("Leaves")]
    public virtual LeaveType LeaveType { get; set; }
}