// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

public partial class LkpGeneralDataCompanyProfile
{
    [Key]
    public int CompanyProfileId { get; set; }

    [Required]
    [StringLength(150)]
    public string NameEn { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string InsuranceNumber { get; set; }

    [Required]
    [StringLength(15)]
    public string TaxNumber { get; set; }

    [StringLength(50)]
    public string PhoneNumber { get; set; }

    [StringLength(50)]
    public string FaxNumber { get; set; }

    [Required]
    [StringLength(50)]
    public string Email { get; set; }

    [Required]
    [StringLength(50)]
    public string WebSite { get; set; }

    [StringLength(256)]
    public string ImageURL { get; set; }

    [StringLength(300)]
    public string Address { get; set; }

    public Guid? CompanyCode { get; set; }

    public int CreatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Company")]
    public virtual ICollection<LkpGeneralDataBranch> LkpGeneralDataBranches { get; set; } = new List<LkpGeneralDataBranch>();
}