// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Table("Offboarding")]
public partial class Offboarding
{
    [Key]
    public int ExitID { get; set; }

    public int? EmployeeID { get; set; }

    [Column(TypeName = "date")]
    public DateTime? ResignationDate { get; set; }

    [StringLength(200)]
    public string ExitReason { get; set; }

    [StringLength(50)]
    public string ClearanceStatus { get; set; }

    public string ExitInterviewNotes { get; set; }
}