// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Table("Onboarding")]
public partial class Onboarding
{
    [Key]
    public int OnboardingID { get; set; }

    public int? EmployeeID { get; set; }

    [Column(TypeName = "date")]
    public DateTime? StartDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? EndDate { get; set; }

    [StringLength(100)]
    public string AssignedMentor { get; set; }

    [StringLength(50)]
    public string ChecklistStatus { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("Onboardings")]
    public virtual Employee Employee { get; set; }
}