// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Table("PerformanceEvaluation")]
public partial class PerformanceEvaluation
{
    [Key]
    public int EvaluationID { get; set; }

    public int? EmployeeID { get; set; }

    [Column(TypeName = "date")]
    public DateTime? Date { get; set; }

    public int? Score { get; set; }

    public string Comments { get; set; }

    public int? EvaluatorID { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("PerformanceEvaluations")]
    public virtual Employee Employee { get; set; }
}