// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[PrimaryKey("EmployeeID", "ProjectID")]
[Table("Project_Assignment")]
public partial class Project_Assignment
{
    [Key]
    public int EmployeeID { get; set; }

    [Key]
    public int ProjectID { get; set; }

    [StringLength(100)]
    public string RoleInProject { get; set; }

    public int? HoursWorked { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("Project_Assignments")]
    public virtual Employee Employee { get; set; }

    [ForeignKey("ProjectID")]
    [InverseProperty("Project_Assignments")]
    public virtual Project Project { get; set; }
}