// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Table("Project")]
public partial class Project
{
    [Key]
    public int ProjectID { get; set; }

    [StringLength(100)]
    public string ProjectName { get; set; }

    [Column(TypeName = "date")]
    public DateTime? StartDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? EndDate { get; set; }

    public int? ManagerID { get; set; }

    [InverseProperty("Project")]
    public virtual ICollection<Project_Assignment> Project_Assignments { get; set; } = new List<Project_Assignment>();
}