// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Table("Recruiter")]
[Index("Email", Name = "UQ__Recruite__A9D10534EC5DC91B", IsUnique = true)]
public partial class Recruiter
{
    [Key]
    public int RecruiterID { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(20)]
    public string Phone { get; set; }

    public int? DepartmentID { get; set; }

    [InverseProperty("Recruiter")]
    public virtual ICollection<Interview> Interviews { get; set; } = new List<Interview>();
}