// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Table("RecruitmentPortal")]
public partial class RecruitmentPortal
{
    [Key]
    public int PortalID { get; set; }

    public int? JobID { get; set; }

    [Column(TypeName = "date")]
    public DateTime? PublishDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? ExpiryDate { get; set; }

    public int? Views { get; set; }

    public int? ApplicationsReceived { get; set; }
}