// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Table("Salary")]
public partial class Salary
{
    [Key]
    public int SalaryID { get; set; }

    public int? EmployeeID { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? BaseSalary { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Bonus { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Deductions { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? NetSalary { get; set; }

    [Column(TypeName = "date")]
    public DateTime? PayDate { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("Salaries")]
    public virtual Employee Employee { get; set; }
}