// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

public partial class SelfServiceRequest
{
    [Key]
    public int RequestID { get; set; }

    public int? EmployeeID { get; set; }

    [StringLength(100)]
    public string RequestType { get; set; }

    [Column(TypeName = "date")]
    public DateTime? RequestDate { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    public int? ApprovedBy { get; set; }
}