// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Table("Survey_Response")]
public partial class Survey_Response
{
    [Key]
    public int ResponseID { get; set; }

    public int? SurveyID { get; set; }

    public int? EmployeeID { get; set; }

    public string ResponseText { get; set; }

    public int? Rating { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("Survey_Responses")]
    public virtual Employee Employee { get; set; }

    [ForeignKey("SurveyID")]
    [InverseProperty("Survey_Responses")]
    public virtual Survey Survey { get; set; }
}