// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Table("Survey")]
public partial class Survey
{
    [Key]
    public int SurveyID { get; set; }

    [StringLength(100)]
    public string Title { get; set; }

    public string Description { get; set; }

    [Column(TypeName = "date")]
    public DateTime? CreatedDate { get; set; }

    [InverseProperty("Survey")]
    public virtual ICollection<Survey_Response> Survey_Responses { get; set; } = new List<Survey_Response>();
}