// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

public partial class Training
{
    [Key]
    public int TrainingID { get; set; }

    [StringLength(100)]
    public string Title { get; set; }

    public string Description { get; set; }

    [Column(TypeName = "date")]
    public DateTime? StartDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? EndDate { get; set; }

    [InverseProperty("Training")]
    public virtual ICollection<Employee_Training> Employee_Trainings { get; set; } = new List<Employee_Training>();
}