// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Table("User")]
[Index("EmployeeID", Name = "IX_User", IsUnique = true)]
[Index("Username", Name = "UQ__User__536C85E4A1E9872A", IsUnique = true)]
public partial class User
{
    [Key]
    public int UserID { get; set; }

    public int EmployeeID { get; set; }

    [StringLength(50)]
    public string Username { get; set; }

    [StringLength(200)]
    public string PasswordHash { get; set; }

    [StringLength(50)]
    public string Role { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("User")]
    public virtual Employee Employee { get; set; }
}